### PR TITLE
Change price of product from USD to NPR

### PR DESCRIPTION
**Pull request by Itezaz-ul-Hassan**
Changed the base price from USD to NPR by multiplying it with **100**.

Here is the change screenshot
image

### CODE REVIEW

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina Fix for this [issue](https://github.com/KriteshTimsina/sastobazaar-ecommerce/issues/11)

**Comment by KriteshTimsina** [comment]
Great approach. But could you make the price comma seperated? Plus, unit and price in most card are breaking, could you just reduce the font-size?

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina Done

**Review by KriteshTimsina — CHANGES_REQUESTED** [review]
Good work @Itezaz-ul-Hassan . Small Request
- You forgot to change tax and service charge to NPR. Simply change the Unit to Rs. 
image

and if you can, could you match the total price in cart page and checkout page.

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina Now everything is in NPR and checkout and cart pages have same total

**Review by diwash007 — CHANGES_REQUESTED** [review]
Thanks for the contribution.
Please resolve the merge conflicts.

**Review by diwash007 — APPROVED** [review]

**Comment by Itezaz-ul-Hassan** [comment]
> Thanks for the contribution. Please resolve the merge conflicts.

@diwash007 Resolved. Please merge it

**Comment by KriteshTimsina** [comment]
GG @Itezaz-ul-Hassan

**Review by KriteshTimsina — COMMENTED** [review]
Great! I found one more issue.

-Try adding first product to cart
-Total becomes 13225
-now,add second items the total becomes 15000
-try removing second item from the cart
-the total stays the same

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina @diwash007 Create a separate issue for this, will do it tomorrow. Meanwhile could you add label `hacktoberfest-accepted` to this PR. I'll start working on this issue so make sure to assign it to me after creating

**Pull request merged**
