### PR TITLE
some ui changes in Card.jsx

### PR DESCRIPTION
**Pull request by saurabhbakolia**
#8 Ui changes issue resolved. 

image

Also alert ⚠ added while click on heart icons.

### CODE REVIEW

**Review by KriteshTimsina — CHANGES_REQUESTED** [review]
Nice work but why don't you add onClick to the div itself not the image as it brings inconsistency in UI. Doing so you can completely ditch wishlist functionality. 

You could:
1. go to product details on clicking anywhere on div and remove wishlist button too
2. OR, go to product details on clicking anywhere but the wishlist button itself.

**Comment by saurabhbakolia** [comment]
ok, but it will more convenient for the user to click on the card to see the details of the product and if user want to add the products to the wishlist, then we can implement the wishlist icon to click on it. 


And now talking about the why I added the click effect on image only. Otherwise, wishlist click will not work as per our need. 

So.

**Comment by KriteshTimsina** [comment]
I understand. But I don't find it user friendly to click on image rather than a card itself. Is there any way you could resolve this issue.?

**Comment by saurabhbakolia** [comment]
ok, then I will implement the onClick on card.

**Comment by KriteshTimsina** [comment]
Implement the wishlist functionality now. Leave products card UI as it is for now

**Pull request closed without merging**
