### PR TITLE
Change product view looking more good and clear.  made it responsive

### LINKED ISSUE #21: Revamp single product page on large screen
Revamp single product page 
Make it look good
Here's the link to what i'm referring to
https://sastobazaar.netlify.app/product/5

### PR DESCRIPTION
**Pull request by supunvindula**
closes #21

### CODE REVIEW

**Comment by supunvindula** [comment]
Hi please add the label hacktoberfest. That was there earlier

**Comment by supunvindula** [comment]
image
I get this error in my hacktoberfest profile regarding this issue. Please can you add the tags as above to the repository and PR

**Review by KriteshTimsina — APPROVED** [review]
LGTM

**Comment by KriteshTimsina** [comment]
Can you check now ? Is your PR counted for hacktoberfest?

**Comment by supunvindula** [comment]
Still it is showing the same. @KriteshTimsina Can you please add hacktoberfest to the topics of the repo? https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by supunvindula** [comment]
Hi @KriteshTimsina its working now. Thank you btw.

**Comment by KriteshTimsina** [comment]
Glad it helped

**Pull request merged**
