### PR TITLE
Added About Us Page.

### PR DESCRIPTION
**Pull request by rohit-chaware**
- Added about us page. 
- You can access it from the footer or with endpoint /about_us.

### CODE REVIEW

**Review by KriteshTimsina — CHANGES_REQUESTED** [review]
This looks great but can you  use icons from react-icons library instead of heroicons. Why use two icons libraries in one project. 
Additionally, Can you add dark mode classes?

**Comment by rohit-chaware** [comment]
Ya sure 👍.

**Comment by rohit-chaware** [comment]
Hii @KriteshTimsina I have added dark mode and used only react-icon library for showing icons.

**Review by KriteshTimsina — APPROVED** [review]
Looks great. Thank you

**Comment by rohit-chaware** [comment]
Welcome ✌️.
Looking forward to contribute more to your project.

**Comment by KriteshTimsina** [comment]
Feel free to check out the repositories and find out bugs or issues.

**Pull request merged**
