### PR TITLE
Product Card Redesigned

### PR DESCRIPTION
**Pull request by RameezIbrahimOfficial**
✅ Fixed the whitespace after Product.
✅Changed product card Design

Screenshot (131)

### CODE REVIEW

**Comment by KriteshTimsina** [comment]
Please resolve the conflict.

**Comment by RameezIbrahimOfficial** [comment]
I have resolved the conflicts with the main branch and pushed the latest changes. Please review the updated PR.

**Comment by RameezIbrahimOfficial** [comment]
@KriteshTimsina Did you check it

**Comment by KriteshTimsina** [comment]
We have decided to stay with the previous design.

**Comment by RameezIbrahimOfficial** [comment]
Ok then i will close the PR

**Comment by RameezIbrahimOfficial** [comment]
Closing the PR

**Pull request closed without merging**
