### PR TITLE
adding FAQ page from footer link

### PR DESCRIPTION
**Pull request by 12345rams**
#20
adding FAQ page from footer link

### CODE REVIEW

**Review by KriteshTimsina — CHANGES_REQUESTED** [review]
Well here are some issue.
-Create a /faq route in App.jsx instead of linking it that way. 
-rename footer with FAQ

**Review by KriteshTimsina — CHANGES_REQUESTED** [review]
Additional request:
- FAQ should expand with answers onClick
- FAQ page must have a title "Frequently Asked Questions"

**Comment by 12345rams** [comment]
done

**Review by KriteshTimsina — CHANGES_REQUESTED** [review]
Please resolve the merge conflict

**Pull request closed without merging**
