### PR TITLE
- [x] slider fadeIn effect working

### LINKED ISSUE #33: Revamp Homepage
Task to accomplish
-Make slider look better in mobile screen.
-add simple fade in animation.
-make it look better 
-add a map component

### PR DESCRIPTION
**Pull request by Ahsan689**
- [x] home page issue resolved
- [x] map component added
- [x] improve slider in mobile view 
- [x] issue closes: #33

### CODE REVIEW

**Review by KriteshTimsina — CHANGES_REQUESTED** [review]
Slider doesn't looks good on mobile screen . can you fix it ??

**Comment by Ahsan689** [comment]
ok sure I will do that

**Review by KriteshTimsina — CHANGES_REQUESTED** [review]
Can you create a separate PR for just the Map functionality ignoring all sliders and other changes.  Sliders on a mobile screen is still looking worse so well resolve it later.

**Comment by Ahsan689** [comment]
I am creating a separate PR for Map so that you can merge it in the code. Can you clarify how you want slider to look in the mobile view.

**Comment by KriteshTimsina** [comment]
No worries. I've already merged the PR linked with #37

**Comment by Ahsan689** [comment]
@KriteshTimsina Thanks man

**Pull request closed without merging**
