### PR TITLE
fix #42 : added wishlist button

### LINKED ISSUE #42: Add "Add to Wishlist" Option on Product Page
I would like to suggest the addition of an "Add to Wishlist" option on the product page.

image

### PR DESCRIPTION
**Pull request by adarsh-site**
image

### CODE REVIEW

**Comment by KriteshTimsina** [comment]
Looks good but user should know if it has been added to wishlist already. In that case, you can show view wishlist button.

**Comment by KriteshTimsina** [comment]
Add please if you're prompting for user whether they want to add or not . Make it a component. Do not use native alert. Or simply remove the alert and directly add it to wishlist. Make sure to implement this logic in both product list as well as product detail screen.

**Comment by adarsh-site** [comment]
@KriteshTimsina 
The alert message have been removed and the view wishlist is added. please check it now.

**Comment by KriteshTimsina** [comment]
@jinx-vi-0 . I'll merge this PR as it looks good to me. Plus, I have assigned to issue related to this PR. It would be great if you could solve these as well.  
Fix this:  issue #44 
Great work

**Pull request merged**
